# Generated by Django 3.1.7 on 2021-04-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_auto_20210324_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.IntegerField(default=0, null=True, verbose_name='like'),
        ),
    ]
