# Generated by Django 3.1.6 on 2021-03-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(default='static/user/images/user.png', upload_to='static/user/images'),
        ),
    ]
