# Generated by Django 3.1.6 on 2021-03-24 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210324_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='like',
        ),
    ]
